<img src="https://github.com/Ch3ddarr/intro-to-eda-and-pandas/blob/main/assets/ga-logo.png?raw=1" style="float: left; margin: 20px; height: 55px">

# EDA with `pandas`

---

### About
`pandas` is the most popular python package for managing datasets and is used extensively by data scientists.

### Learning Objectives
- Explore the characteristics of a data set at a high level with `pandas`.

### Notebook Guide
- Reading data with `pandas`
- Exploring and manipulating data with `pandas`
    - Column operations
    - Filtering
    - Sorting
    - Exporting data
- Conclusions and Takeaways

# Scenario

You're an analyst working for CoolBricks - a new toy company who wants to compete with LEGO by producing their own bricks and sets. To better understand what kind of sets to create and at what price points, you are tasked with analyzing LEGO's catalogue over time.

The data comes from Kaggle: [https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time](https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time)

We are going to use `pandas` to read and explore this data.

This notebook will showcase some fundamental `pandas` features and commands and in notebook 3, you will answer some questions about the data, and therefore the business question, on your own.

## Loading a CSV into a `DataFrame`

Use this link to read the CSV file:
https://raw.githubusercontent.com/juanatga/intro-to-eda-and-pandas/main/data/lego.csv

In [1]:
import pandas as pd

We'll read in the data. The `read_csv` method has lots of options, but the defaults are usually a good place to start.

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/juanatga/intro-to-eda-and-pandas/main/data/lego.csv", storage_options = {'User-Agent':'Our world in Lego Data/1.0'})

Let's look at the data!

In [4]:
df

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},16.0,NaN,10.0,0.0,NaN,NaN,NaN
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},20.0,NaN,11.0,0.0,NaN,NaN,NaN
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,{Not specified},0,{Not specified},21.0,NaN,10.0,0.0,NaN,0.0,NaN
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},32.0,NaN,8.0,0.0,NaN,NaN,NaN
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},330.0,NaN,10.0,0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14931,854242-1,Creeper Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN
14932,854243-1,Steve Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN
14933,854244-1,Piglin Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN
14934,854245-1,Fennec Shand Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,NaN,88.0,0.0,5.99,NaN,NaN
14935,854246-1,Scout Trooper Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,NaN,107.0,0.0,5.99,NaN,NaN

In [ ]:
df.head(6)

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},16.0,NaN,10.0,0.0,NaN,NaN,NaN
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},20.0,NaN,11.0,0.0,NaN,NaN,NaN
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,{Not specified},0,{Not specified},21.0,NaN,10.0,0.0,NaN,0.0,NaN
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},32.0,NaN,8.0,0.0,NaN,NaN,NaN
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},330.0,NaN,10.0,0.0,NaN,0.0,NaN
5,133-1,Locomotive,1975,Trains,Modern day,4.5/12V,Normal,{Not specified},0,{Not specified},87.0,NaN,279.0,0.0,NaN,0.0,NaN

In [ ]:
df.columns

Index(['Set_ID', 'Name', 'Year', 'Theme', 'Theme_Group', 'Subtheme',
       'Category', 'Packaging', 'Num_Instructions', 'Availability', 'Pieces',
       'Minifigures', 'Owned', 'Rating', 'USD_MSRP', 'Total_Quantity',
       'Current_Price'],
      dtype='object')

# Column Operations
---

There are some columns we don't need, such as how many users on a specific platform claim to own each set. Let's remove the "Owned" column.

In [ ]:
# Drop is used to delete several columns from the df
cleaned_data = df.drop(columns=["Packaging"])
cleaned_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14936 entries, 0 to 14935
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Set_ID            14936 non-null  object
 1   Name              14936 non-null  object
 2   Year              14936 non-null  int64
 3   Theme             14936 non-null  object
 4   Theme_Group       14915 non-null  object
 5   Subtheme          11495 non-null  object
 6   Category          14936 non-null  object
 7   Num_Instructions  14936 non-null  int64
 8   Availability      14936 non-null  object
 9   Pieces            13133 non-null  float64
 10  Minifigures       7686 non-null   float64
 11  Owned             14771 non-null  float64
 12  Rating            14936 non-null  float64
 13  USD_MSRP          5837 non-null   float64
 14  Total_Quantity    12276 non-null  float64
 15  Current_Price     5442 non-null   float64
dtypes: float64(7), int64(2), object(7)
memory usage: 1.8+ MB

OK let's take a look at the data again

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14936 entries, 0 to 14935
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Set_ID            14936 non-null  object
 1   Name              14936 non-null  object
 2   Year              14936 non-null  int64
 3   Theme             14936 non-null  object
 4   Theme_Group       14915 non-null  object
 5   Subtheme          11495 non-null  object
 6   Category          14936 non-null  object
 7   Packaging         14936 non-null  object
 8   Num_Instructions  14936 non-null  int64
 9   Availability      14936 non-null  object
 10  Pieces            13133 non-null  float64
 11  Minifigures       7686 non-null   float64
 12  Owned             14771 non-null  float64
 13  Rating            14936 non-null  float64
 14  USD_MSRP          5837 non-null   float64
 15  Total_Quantity    12276 non-null  float64
 16  Current_Price     5442 non-null   float64
dtypes: float64(7), int64(2), object(8)
memory usage: 1.9+ MB

In [ ]:
df.drop(columns=["Packaging", "Owned", "Pieces"])

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Num_Instructions,Availability,Minifigures,Rating,USD_MSRP,Total_Quantity,Current_Price
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,0,{Not specified},NaN,0.0,NaN,NaN,NaN
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,0,{Not specified},NaN,0.0,NaN,NaN,NaN
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,0,{Not specified},NaN,0.0,NaN,0.0,NaN
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,0,{Not specified},NaN,0.0,NaN,NaN,NaN
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,0,{Not specified},NaN,0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14931,854242-1,Creeper Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,0,LEGO exclusive,NaN,0.0,5.99,NaN,NaN
14932,854243-1,Steve Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,0,LEGO exclusive,NaN,0.0,5.99,NaN,NaN
14933,854244-1,Piglin Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,0,LEGO exclusive,NaN,0.0,5.99,NaN,NaN
14934,854245-1,Fennec Shand Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,0,LEGO exclusive,NaN,0.0,5.99,NaN,NaN
14935,854246-1,Scout Trooper Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,0,LEGO exclusive,NaN,0.0,5.99,NaN,NaN

What?! The `Owned` column is still there, but we saw it disappear above!

This is because `pandas` operations almost always return a **copy** of the data without changing the underlying data set.

To make an operation permanent, you need to explicitly overwrite your `DataFrame` object:

In [ ]:
#If we want to remove the column from a dataframe we have to set argument inplace = True, bat that's not something that's recommended

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Rating,USD_MSRP,Total_Quantity,Current_Price
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},16.0,NaN,0.0,NaN,NaN,NaN
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},20.0,NaN,0.0,NaN,NaN,NaN
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,{Not specified},0,{Not specified},21.0,NaN,0.0,NaN,0.0,NaN
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},32.0,NaN,0.0,NaN,NaN,NaN
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},330.0,NaN,0.0,NaN,0.0,NaN

Let's limit our data to only the most recent sets, say the last 10 years.

To do this we will:

- calculate the age of each set
- filter out anything older than 10 years

To create new columns, we can perform a vectorized operation on the entire column (not loop through its values):

In [ ]:
# Ovo su dva nacina da se filterisu kolone
# clean_data = df[df["Year"] >= 2016]
# clean_data

# df['Age'] = 2026 - df['Year']
# new_df = df[df['Age'] <= 10]
# new_df

# import datetime
# current_year = datetime.datetime.today().year
# df['Age'] = current_year - df["Year"]

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price,Age
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},16.0,NaN,10.0,0.0,NaN,NaN,NaN,51
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},20.0,NaN,11.0,0.0,NaN,NaN,NaN,51
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,{Not specified},0,{Not specified},21.0,NaN,10.0,0.0,NaN,0.0,NaN,51
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},32.0,NaN,8.0,0.0,NaN,NaN,NaN,51
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},330.0,NaN,10.0,0.0,NaN,0.0,NaN,51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14931,854242-1,Creeper Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN,3
14932,854243-1,Steve Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN,3
14933,854244-1,Piglin Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN,3
14934,854245-1,Fennec Shand Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,NaN,88.0,0.0,5.99,NaN,NaN,3
14935,854246-1,Scout Trooper Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,NaN,107.0,0.0,5.99,NaN,NaN,3

To create a new column, we use syntax similar to adding a key to a dictionary

#### Reflection

How is this different from working with Python types, like numbers or lists?

---

When we look at the data, our new column will be at the end

In [ ]:
new_df

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price,Age
10936,10251-1,Brick Bank,2016,Creator Expert,Model making,Modular Buildings Collection,Normal,Box,2,LEGO exclusive,2380.0,5.0,20785.0,4.4,169.99,23.0,597.62,10
10937,10252-1,Volkswagen Beetle,2016,Creator Expert,Model making,Vehicles,Normal,Box,2,LEGO exclusive,1167.0,NaN,15815.0,4.3,99.99,15.0,157.00,10
10938,10253-1,Big Ben,2016,Creator Expert,Model making,Landmarks,Normal,Box,2,LEGO exclusive,4163.0,NaN,6885.0,4.2,249.99,3.0,395.00,10
10939,10254-1,Winter Holiday Train,2016,Creator Expert,Model making,Winter Village Collection,Normal,Box,4,LEGO exclusive,734.0,5.0,17138.0,4.1,99.99,28.0,225.00,10
10940,10654-1,XL Creative Brick Box,2016,Classic,Basic,Creative Box,Normal,Box,0,Retail - limited,1600.0,NaN,899.0,4.0,NaN,0.0,NaN,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14931,854242-1,Creeper Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN,3
14932,854243-1,Steve Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN,3
14933,854244-1,Piglin Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN,3
14934,854245-1,Fennec Shand Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,NaN,88.0,0.0,5.99,NaN,NaN,3
14935,854246-1,Scout Trooper Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,NaN,107.0,0.0,5.99,NaN,NaN,3

We can select multiple columns to verify the new age column. To do this, pass a list instead of a single column name.

# Filtering
---

Now, we can use our new column to find only the newest sets.

To filter a `DataFrame` we need:

1. A filter to apply (like a `WHERE` clause in SQL)
2. To apply this filter to the `DataFrame`

With `pandas`, even boolean operations are vectorized!

We can save that filter into a variable, then use it to index the `DataFrame`

We can also combine those steps (you'll see this a lot)

We could also save this filtered version into a new `DataFrame` variable

This is a copy, so changes to this `DataFrame` **do not affect the original `DataFrame`** but if we tried to make any changes to it we'll get a warning

This warning is just a reminder that:

- `filtered` is a "slice" of the original `lego` `DataFrame`
- it is a **copy**, so any changes to `filtered` **will not affect** `lego`

To make this go away, you can be explicit about the fact that we are copying data:

No warning!

### Multiple Filters

What about only looking at new sets that have a Star Wars theme?

To combine multiple filters:

1. Each filter needs to be parenthesized
2. Instead of Python's `and` we use `&` and instead of `or` we use `|`

In [ ]:
lego[(lego["Age"] < 10) & (lego["Theme"] == "Star Wars")]

In [ ]:
lego[(lego["Age"] < 10) | (lego["Theme"] == "Star Wars")]

# Sorting
---

Let's find the most expensive LEGO sets. To do this, we need to sort our data.

Sorting is done by calling `.sort_values()` on the `DataFrame` and specifying the column.

In [9]:
clean_data = df.sort_values('Availability')
clean_data

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price
6780,9764-1,Power Puzzle Challenge Kit,2007,Education,Educational,FIRST LEGO League Challenge,Normal,Box,0,Educational,1563.0,1.0,27.0,0.0,NaN,0.0,NaN
12231,45806-1,INTO ORBIT Challenge Kit,2018,Education,Educational,FIRST LEGO League Challenge,Normal,Box,0,Educational,1892.0,3.0,57.0,0.0,NaN,0.0,NaN
12232,45807-1,Mission MOON Inspire Set,2018,Education,Educational,FIRST LEGO League Explore,Normal,Box,0,Educational,693.0,NaN,32.0,0.0,NaN,0.0,NaN
9436,9664-1,Nature's Fury Challenge Kit,2013,Education,Educational,FIRST LEGO League Challenge,Normal,Box,0,Educational,2031.0,3.0,48.0,0.0,NaN,0.0,NaN
12233,45808-1,Mission MOON Discovery Set,2018,Education,Educational,FIRST LEGO League Discover,Normal,Box,0,Educational,50.0,NaN,4.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9928,850648-1,Teenage Mutant Ninja Turtles Leonardo Key Chain,2013,Gear,Miscellaneous,Key Chains/Teenage Mutant Ninja Turtles,Gear,{Not specified},0,{Not specified},NaN,NaN,480.0,0.0,4.99,NaN,NaN
9927,850646-1,Teenage Mutant Ninja Turtles Donatello Key Chain,2013,Gear,Miscellaneous,Key Chains/Teenage Mutant Ninja Turtles,Gear,{Not specified},0,{Not specified},NaN,NaN,490.0,0.0,4.99,NaN,NaN
9926,850644-1,Yoda Magnet,2013,Gear,Miscellaneous,Magnets/Star Wars,Gear,{Not specified},0,{Not specified},NaN,NaN,369.0,0.0,6.99,NaN,NaN
5890,7558-1,Shells and Starfish,2005,Clikits,Girls,NaN,Normal,{Not specified},0,{Not specified},14.0,NaN,80.0,0.0,NaN,2.0,7.833
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},16.0,NaN,10.0,0.0,NaN,NaN,NaN

The default is ascending order, so to sort in descending order we specify `ascending=False`

In [11]:
new_clean_data = df.sort_values('Availability', ascending=False)
new_clean_data

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},16.0,NaN,10.0,0.0,NaN,NaN,NaN
5753,4868-1,Rahaga Gaaki,2005,Bionicle,Constraction,Rahaga,Normal,{Not specified},1,{Not specified},28.0,NaN,1597.0,3.6,NaN,0.0,NaN
5792,5462-1,Bathtime Boat,2005,Baby,Pre-school,NaN,Normal,{Not specified},0,{Not specified},4.0,1.0,67.0,0.0,NaN,0.0,NaN
5791,5461-1,Shape Sorter House,2005,Baby,Pre-school,NaN,Normal,{Not specified},0,{Not specified},12.0,NaN,55.0,0.0,NaN,0.0,NaN
5790,5460-1,Happy Flower Rattle & Teether,2005,Baby,Pre-school,NaN,Normal,{Not specified},0,{Not specified},2.0,NaN,51.0,0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11180,45018-1,Build Me 'Emotions',2016,Education,Educational,Duplo,Normal,Box,0,Educational,188.0,NaN,29.0,0.0,94.95,0.0,NaN
11183,45300-1,WeDo 2.0 Core Set,2016,Education,Educational,NaN,Normal,Tub,0,Educational,280.0,NaN,242.0,0.0,224.95,3.0,250.0
11184,45301-1,WeDo 2.0 Smart Hub,2016,Education,Educational,NaN,Normal,{Not specified},0,Educational,1.0,NaN,17.0,0.0,NaN,0.0,NaN
11185,45302-1,WeDo 2.0 Smarthub Rechargeable Battery,2016,Education,Educational,NaN,Normal,{Not specified},0,Educational,1.0,NaN,22.0,0.0,NaN,7.0,17.0
13211,45813-1,RePLAY Challenge Kit,2020,Education,Educational,FIRST LEGO League Challenge,Normal,Box,1,Educational,1634.0,2.0,29.0,0.0,NaN,0.0,NaN

# Exporting data
---

For now, we will report to our stakeholders that Star Wars sets seem to command high prices. We will export the most recent Star Wars sets to a separate `DataFrame`

`pandas` also supports many *export* formats, like CSVs

In [19]:
star_wars = df[df['Theme'] =='Star Wars']
# star_wars --> checking the new dataset

star_wars.to_csv("star_wars.csv")

from google.colab import files
files.download('star_wars.csv')

# Conclusions and Takeaways
---

- `pandas` is the most popular data analysis library in the Python ecosystem
- `pandas` introduces the `Series` and `DataFrame` types to make manipulating data easier
- `pandas` uses vectorized operations to manipulate entire columns at once
- most operations return *copies* of the data, so users must be explicit when overwriting their data

#### Reflect

Make sure you understand:

- why working with `pandas` is more efficient than working with Python objects like lists
- what the difference between a `DataFrame` and a `Series` is
- that most of the time `pandas` operations return **copies** of the data